In [1]:
import psycopg2
import pandas as pd
import os
from dotenv import load_dotenv
import datetime

In [2]:
load_dotenv(dotenv_path='../.env')

True

In [3]:
POSTGRES_PASS = os.getenv("POSTGRES_PASS")

In [4]:
conn = psycopg2.connect(
    dbname="puppet_db",
    user="postgres",
    password=POSTGRES_PASS,
    host="localhost",
    port="5432"
)

In [5]:
# Example query to fetch all customers
query = "SELECT * FROM customer;"
df = pd.read_sql_query(query, conn)
df

C:\Users\quinb\AppData\Local\Temp\ipykernel_10932\328603788.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,customer_key,first_name,last_name,source_system_name,dob,gender,create_timestamp
0,C001,John,Doe,System_A,1985-07-14,Male,2025-02-06 10:00:00
1,C002,Jane,Smith,System_B,1990-03-21,Female,2025-02-06 11:00:00
2,C003,Sam,Brown,System_A,1982-05-15,Male,2025-02-06 12:00:00
3,C004,Emily,Davis,System_C,1995-09-30,Female,2025-02-06 13:00:00

In [6]:
query = "SELECT * FROM teams;"

In [7]:
query = "SELECT * FROM items;"

In [8]:
query = "SELECT * FROM heroes;"

In [9]:
query = "SELECT * FROM matches;"

In [10]:
query = "SELECT * FROM players;"

In [15]:
table_name = "items"

In [16]:
query = f"SELECT * FROM {table_name};"
df = pd.read_sql_query(query, conn)
df

C:\Users\quinb\AppData\Local\Temp\ipykernel_10932\2503781699.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

                 item_id                 name    cost
0                  blink         Blink Dagger  2250.0
1     overwhelming_blink   Overwhelming Blink  6800.0
2            swift_blink          Swift Blink  6800.0
3           arcane_blink         Arcane Blink  6800.0
4    recipe_arcane_blink  Arcane Blink Recipe  1750.0
..                   ...                  ...     ...
454             doubloon             Doubloon     0.0
455       roshans_banner      Roshan's Banner     0.0
456       black_grimoire       Black Grimoire     0.0
457             grisgris            Gris-Gris     0.0
458     diffusal_blade_2       Diffusal Blade  3850.0

[459 rows x 3 columns]