In [1]:
import psycopg2
import pandas as pd
import os
from dotenv import load_dotenv
import datetime

In [2]:
load_dotenv(dotenv_path='../.env')

True

In [3]:
POSTGRES_PASS = os.getenv("POSTGRES_PASS")
conn = psycopg2.connect(
    dbname="puppet_db",
    user="postgres",
    password=POSTGRES_PASS,
    host="localhost",
    port="5432"
)

In [14]:
query = "SELECT match_id, start_time, duration \
FROM matches \
WHERE duration > 400 \
LIMIT 10;"

In [16]:
query = "SELECT match_id, start_time, duration \
FROM matches;"

In [17]:
df = pd.read_sql_query(query, conn)
df

C:\Users\quinb\AppData\Local\Temp\ipykernel_21956\51381808.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

     match_id  start_time  duration
0  8165111506  1739028497       674
1  8165106813  1739028322       630
2  8165105310  1739028283       400
3  8165104917  1739028267       399
4  8165103712  1739028222       526

In [15]:
table_name = "items"

In [16]:
query = f"SELECT * FROM {table_name};"
df = pd.read_sql_query(query, conn)
df

C:\Users\quinb\AppData\Local\Temp\ipykernel_10932\2503781699.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

                 item_id                 name    cost
0                  blink         Blink Dagger  2250.0
1     overwhelming_blink   Overwhelming Blink  6800.0
2            swift_blink          Swift Blink  6800.0
3           arcane_blink         Arcane Blink  6800.0
4    recipe_arcane_blink  Arcane Blink Recipe  1750.0
..                   ...                  ...     ...
454             doubloon             Doubloon     0.0
455       roshans_banner      Roshan's Banner     0.0
456       black_grimoire       Black Grimoire     0.0
457             grisgris            Gris-Gris     0.0
458     diffusal_blade_2       Diffusal Blade  3850.0

[459 rows x 3 columns]